### ISSUE TITLE
newFollowers don't works

### ISSUE THREAD

**Issue by TapsHTS** [Androz2091/insta.js#18]
I want to send a message if the user follow the bot, but nothing happens, no error, no message.

```js
clienti.on('newFollower', (user) => {
    console.log('╭───────────────────────────╮')
    console.log('| ➜    Nouveau follower !  |')
    console.log('╰───────────────────────────╯')
    user.send('🛬 Merci d\'utiliser pro_note_ !');
});```

**Comment by TapsHTS** [comment]
```(node:24) UnhandledPromiseRejectionWarning: IgResponseError: POST /api/v1/direct_v2/threads/broadcast/link/ - 400 Bad Request;
at Request.handleResponseError (/home/container/node_modules/instagram-private-api/dist/core/request.js:125:16)
at Request.send (/home/container/node_modules/instagram-private-api/dist/core/request.js:53:28)
at async DirectThreadRepository.broadcast (/home/container/node_modules/instagram-private-api/dist/repositories/direct-thread.repository.js:176:26)
at async DirectThreadEntity.broadcast (/home/container/node_modules/instagram-private-api/dist/entities/direct-thread.entity.js:180:26)
at async DirectThreadEntity.broadcastLink (/home/container/node_modules/instagram-private-api/dist/entities/direct-thread.entity.js:69:16)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)```

Code: ```js
clienti.on('newFollower', async (user) => {
    console.log('╭───────────────────────────╮')
    console.log('| ➜    Nouveau follower !  |')
    console.log('╰───────────────────────────╯')
    if (!user.privateChat) await user.fetchPrivateChat()
    user.privateChat.sendMessage('🚀 Merci d\'utiliser pro_note.bot!')



```

**Comment by kaiquebarreto** [comment]
I'm having the same problem!
