### ISSUE TITLE
Groups problem

### ISSUE THREAD

**Issue by Mr-KayJayDee** [Androz2091/insta.js#22]
When you make an user admin in a groups you get an error: 
```bash
(node:10408) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\minit\Desktop\CODING\JS\InstaBot\node_modules\@androz2091\insta.js\src\structures\Client.js:171:53
    at Array.forEach (<anonymous>)
    at C:\Users\minit\Desktop\CODING\JS\InstaBot\node_modules\@androz2091\insta.js\src\structures\Client.js:128:33
    at Array.forEach (<anonymous>)
    at InstaBot.handleRealtimeReceive (C:\Users\minit\Desktop\CODING\JS\InstaBot\node_modules\@androz2091\insta.js\src\structures\Client.js:127:25)
    at RealtimeClient.<anonymous> (C:\Users\minit\Desktop\CODING\JS\InstaBot\node_modules\@androz2091\insta.js\src\structures\Client.js:269:61)
    at RealtimeClient.emit (events.js:314:20)
    at SafeSubscriber._next (C:\Users\minit\Desktop\CODING\JS\InstaBot\node_modules\instagram_mqtt\dist\realtime\realtime.client.js:120:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
And this error when you add / remove an user to the group

```bash
(node:10408) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'messages' of undefined
    at C:\Users\minit\Desktop\CODING\JS\InstaBot\node_modules\@androz2091\insta.js\src\structures\Client.js:184:47
    at Array.forEach (<anonymous>)
    at C:\Users\minit\Desktop\CODING\JS\InstaBot\node_modules\@androz2091\insta.js\src\structures\Client.js:128:33
    at Array.forEach (<anonymous>)
    at InstaBot.handleRealtimeReceive (C:\Users\minit\Desktop\CODING\JS\InstaBot\node_modules\@androz2091\insta.js\src\structures\Client.js:127:25)
    at RealtimeClient.<anonymous> (C:\Users\minit\Desktop\CODING\JS\InstaBot\node_modules\@androz2091\insta.js\src\structures\Client.js:269:61)
    at RealtimeClient.emit (events.js:314:20)
    at SafeSubscriber._next (C:\Users\minit\Desktop\CODING\JS\InstaBot\node_modules\instagram_mqtt\dist\realtime\realtime.client.js:120:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Androz2091** [comment]
Fixed with v1.4.0
