### ISSUE TITLE
Chat fetch doesn't work

### ISSUE THREAD

**Issue by busybox11** [Androz2091/insta.js#35]
When I try to fetch a channel, it doesn't work. Here is the full stack trace.

```NODE
(node:4096) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'feed' of null
    at Client.fetchChat (/home/busybox/dev/insta-discord/node_modules/@androz2091/insta.js/src/structures/Client.js:111:59)
    at Client.<anonymous> (/home/busybox/dev/insta-discord/index.js:52:14)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/busybox/dev/insta-discord/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/busybox/dev/insta-discord/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/busybox/dev/insta-discord/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/busybox/dev/insta-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/busybox/dev/insta-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/busybox/dev/insta-discord/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/busybox/dev/insta-discord/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/busybox/dev/insta-discord/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/busybox/dev/insta-discord/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/busybox/dev/insta-discord/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/busybox/dev/insta-discord/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Receiver.Writable.write (_stream_writable.js:303:10)
    at TLSSocket.socketOnData (/home/busybox/dev/insta-discord/node_modules/ws/lib/websocket.js:872:35)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:4096) TypeError: Cannot read property 'feed' of null
    at Client.fetchChat (/home/busybox/dev/insta-discord/node_modules/@androz2091/insta.js/src/structures/Client.js:111:59)
    at Client.<anonymous> (/home/busybox/dev/insta-discord/index.js:52:14)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/busybox/dev/insta-discord/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/busybox/dev/insta-discord/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/busybox/dev/insta-discord/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/busybox/dev/insta-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/busybox/dev/insta-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/busybox/dev/insta-discord/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/busybox/dev/insta-discord/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/busybox/dev/insta-discord/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/busybox/dev/insta-discord/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/busybox/dev/insta-discord/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/busybox/dev/insta-discord/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Receiver.Writable.write (_stream_writable.js:303:10)
    at TLSSocket.socketOnData (/home/busybox/dev/insta-discord/node_modules/ws/lib/websocket.js:872:35)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
```

**Comment by busybox11** [comment]
It does work. I'm just dumb, I swapped Instagram and Discord clients...
