### ISSUE TITLE
I get ClientDisconnectedError with basic example

### ISSUE THREAD

**Issue by dcts** [Androz2091/insta.js#39]
When I recreate the basic example, I receive a `ClientDisconnectedError`. This happens almost every time I send a message, but also approximately every 20 seconds (even when not sending a message). But the messages still get propagated and I can display them locally, which is great. But I am wondering what causes the error, it seems risky to me just ignoring this error. Heres the full error:
```
ClientDisconnectedError: MQTToTClient got disconnected.
    at SafeSubscriber._next (/home/instjstest/node_modules/instagram_mqtt/dist/realtime/realtime.client.js:154:30)
    at SafeSubscriber.__tryOrUnsub (/home/instjstest/node_modules/mqtts/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/instjstest/node_modules/mqtts/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/home/instjstest/node_modules/mqtts/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/home/instjstest/node_modules/mqtts/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/home/instjstest/node_modules/mqtts/node_modules/rxjs/internal/Subject.js:60:25)
    at MQTToTClient.setDisconnected (/home/instjstest/node_modules/mqtts/dist/mqtt.client.js:330:30)
    at Object.disconnect (/home/instjstest/node_modules/mqtts/dist/mqtt.client.js:98:26)
    at TLSSocket.<anonymous> (/home/instjstest/node_modules/mqtts/dist/transport/tls.transport.js:36:52)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

What could cause this error?

**Comment by dcts** [comment]
Sorry the issue was for me that I unfortunately had 2 instances running, which lead to this error. Running only 1 instance worked great!
