### ISSUE TITLE
ConnectionFailedError while trying to login the client

### ISSUE THREAD

**Issue by dcts** [Androz2091/insta.js#51]
For me the repo somehow stopped working. I have multiple bots running and all of them consistently show the following error when trying to log in:
```
(node:27822) UnhandledPromiseRejectionWarning: ConnectionFailedError: CONNACK returnCode: 3 errorName: Server unavailable
    at Object.next (/home/dcts/code/insta.js/node_modules/instagram_mqtt/dist/mqttot/mqttot.client.js:72:23)
    at MQTToTClient.continueFlows (/home/dcts/code/insta.js/node_modules/mqtts/dist/mqtt.client.js:212:104)
    at MQTToTClient.handlePacket (/home/dcts/code/insta.js/node_modules/mqtts/dist/mqtt.client.js:291:19)
    at /home/dcts/code/insta.js/node_modules/mqtts/dist/mqtt.client.js:247:43
    at Array.forEach (<anonymous>)
    at MQTToTClient.parseData (/home/dcts/code/insta.js/node_modules/mqtts/dist/mqtt.client.js:247:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:27822) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27822) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Anyone having the same issue? 

I investigated a bit and the piece of code inside the client class that causes the error is [this one](https://github.com/Androz2091/insta.js/blob/c4f6038d7aa85c3e2be3d7ea70ae2d7ae3c95334/src/structures/Client.js#L390)

**Comment by kashirin-dm** [comment]
The same if I'll try to login after successful login without logout.

**Comment by Androz2091** [comment]
Please open an issue at https://github.com/Nerixyz/instagram_mqtt
