### ISSUE TITLE
429 - Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by nerkoux** [Androz2091/insta.js#53]
Application Logs

>2021-03-10T00:33:39.746440+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: IgResponseError: POST /api/v1/direct_v2/threads/broadcast/text/ - 429 -; Please wait a few minutes before you try again.
2021-03-10T00:33:39.746448+00:00 app[worker.1]:     at Request.handleResponseError (/app/node_modules/instagram-private-api/dist/core/request.js:125:16)
2021-03-10T00:33:39.746449+00:00 app[worker.1]:     at Request.send (/app/node_modules/instagram-private-api/dist/core/request.js:53:28)
2021-03-10T00:33:39.746450+00:00 app[worker.1]:     at async DirectThreadRepository.broadcast (/app/node_modules/instagram-private-api/dist/repositories/direct-thread.repository.js:176:26)
2021-03-10T00:33:39.746450+00:00 app[worker.1]:     at async DirectThreadEntity.broadcast (/app/node_modules/instagram-private-api/dist/entities/direct-thread.entity.js:192:26)
2021-03-10T00:33:39.746451+00:00 app[worker.1]:     at async DirectThreadEntity.broadcastText (/app/node_modules/instagram-private-api/dist/entities/direct-thread.entity.js:26:16)
2021-03-10T00:33:39.746452+00:00 app[worker.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-03-10T00:33:39.746533+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-03-10T00:33:39.746595+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dcts** [comment]
This error occurs when instagram blocks you, see http response code 429. I have this some time, then I wait usually 1 hour (without touching the bot) and it should work again.
