### ISSUE TITLE
I've an instagram bot which used to work earlier . But now if i'm running the code , I'm getting this error

### ISSUE THREAD

**Issue by nerkoux** [Androz2091/insta.js#59]
`(node:40) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of undefined`

**Comment by byteakshat** [comment]
`at new Message (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Message.js:84:83)
    at /home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:76:49
    at Array.forEach (<anonymous>)
    at Chat._patch (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:75:24)
    at new Chat (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:53:14)
    at /home/runner/dobbie1/node_modules/@androz2091/insta.js/s
Promise { <pending> }
Hint: hit control+c anytime to enter REPL.
(node:81) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 messageCreate listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
BOT IS ONLINE
(node:81) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of undefined
    at new Message (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Message.js:84:83)
    at /home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:76:49
    at Array.forEach (<anonymous>)
    at Chat._patch (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:75:24)
    at new Chat (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:53:14)
    at /home/runner/dobbie1/node_modules/@androz2091/insta.js/s
Promise { <pending> }
Hint: hit control+c anytime to enter REPL.
(node:166) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 messageCreate listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
BOT IS ONLINE
(node:166) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of undefined
    at new Message (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Message.js:84:83)
    at /home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:76:49
    at Array.forEach (<anonymous>)
    at Chat._patch (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:75:24)
    at new Chat (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:53:14)
    at /home/runner/dobbie1/node_modules/@androz2091/insta.js/s
Promise { <pending> }
Hint: hit control+c anytime to enter REPL.
(node:219) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 messageCreate listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
BOT IS ONLINE
(node:219) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of undefined
    at new Message (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Message.js:84:83)
    at /home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:76:49
    at Array.forEach (<anonymous>)
    at Chat._patch (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:75:24)
    at new Chat (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Chat.js:53:14)
    at /home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Client.js:374:26
    at Array.forEach (<anonymous>)
    at Client.login (/home/runner/dobbie1/node_modules/@androz2091/insta.js/src/structures/Client.js:373:17)
(node:219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:219) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Androz2091** [comment]
fixed
