### ISSUE TITLE
IgResponseError: POST /api/v1/accounts/login/

### ISSUE THREAD

**Issue by 89z** [Androz2091/insta.js#74]
Using this program:

~~~js
const Insta = require('@androz2091/insta.js');
const client = new Insta.Client();

client.on('connected', () => {
    console.log(`Logged in as ${client.user.username}`);
});

client.login('srpen6', 'PASSWORD');
~~~

I get this result:

~~~
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

IgResponseError: POST /api/v1/accounts/login/ - 400 Bad Request; Please wait a
few minutes before you try again.
    at Request.handleResponseError (D:\Desktop\node_modules\instagram-private-api\dist\core\request.js:125:16)
    at Request.send (D:\Desktop\node_modules\instagram-private-api\dist\core\request.js:53:28)
~~~

**Comment by 89z** [comment]
Closing this in favor of my own package:

https://github.com/89z/mech/tree/master/instagram
