### ISSUE TITLE
IgResponseError: POST /api/v1/launcher/sync/ - 429 Too Many Requests; 

### ISSUE THREAD

**Issue by pedroherpeto** [Androz2091/insta.js#75]
Hi everyone, im getting this error using the basic configuration! some one know something about it?

(node:10416) UnhandledPromiseRejectionWarning: IgResponseError: POST /api/v1/launcher/sync/ - 429 Too Many Requests; 
    at Request.handleResponseError (C:\insta.js\node_modules\instagram-private-api\dist\core\request.js:125:16)
    at Request.send (C:\insta.js\node_modules\instagram-private-api\dist\core\request.js:53:28)
    at async LauncherRepository.sync (C:\insta.js\node_modules\instagram-private-api\dist\repositories\launcher.repository.js:22:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the 
Node.js process with a non-zero exit code.

**Comment by pedroherpeto** [comment]
solved!
