### ISSUE TITLE
IgResponseError: POST /api/v1/accounts/msisdn_header_bootstrap/ - 302 Found;

### ISSUE THREAD

**Issue by mupalvan** [Androz2091/insta.js#80]
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

IgResponseError: POST /api/v1/accounts/msisdn_header_bootstrap/ - 302 Found; 
    at Request.handleResponseError (f:\temp\instaapi\node_modules\instagram-private-api\dist\core\request.js:126:16)
    at Request.send (f:\temp\instaapi\node_modules\instagram-private-api\dist\core\request.js:54:28)
    at async AccountRepository.msisdnHeaderBootstrap (f:\temp\instaapi\node_modules\instagram-private-api\dist\repositories\account.repository.js:251:26)

**What is the problem????????????????????**

**Comment by ghost** [comment]
same issue here

**Comment by salman0ansari** [comment]
https://github.com/Androz2091/insta.js/issues/65#issuecomment-900892635
