### ISSUE TITLE
throw new errors_1.IgNetworkError(err);

### ISSUE THREAD

**Issue by mupalvan** [Androz2091/insta.js#88]
![Screenshot_2023-06-21-18-03-13-153_com termux](https://github.com/Androz2091/insta.js/assets/77997241/cbf30111-07ed-47cb-93ca-ad24ed378b8c)

**Comment by Lohuama** [comment]
I have the same problem 

npm ERR! code 1
npm ERR! path C:\Users\lohuama\Documents\insta.js-master\node_modules\re2
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR
npm ERR! No github repository was identified.
npm ERR! Building locally ...
npm ERR!
npm ERR! > re2@1.15.4 rebuild
npm ERR! > node-gyp rebuild
npm ERR! npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.0
npm ERR! gyp info using node@16.16.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.5 found at "C:\Python311\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.33927.289) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! (node:5140) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn C:\Python311\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\lohuama\\Documents\\insta.js-master\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\lohuama\\Documents\\insta.js-master\\node_modules\\re2\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\lohuama\\Documents\\insta.js-master\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\lohuama\\AppData\\Local\\node-gyp\\Cache\\16.16.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\lohuama\\AppData\\Local\\node-gyp\\Cache\\16.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\lohuama\\Documents\\insta.js-master\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\lohuama\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.16.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\lohuama\\Documents\\insta.js-master\\node_modules\\re2',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\lohuama\\Documents\\insta.js-master\\node_modules\\re2\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\lohuama\Documents\insta.js-master\node_modules\node-gyp\gyp\gyp_main.py", line 51, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!              ^^^^^^^^^^^^^^^^^
npm ERR!   File "C:\Users\lohuama\Documents\insta.js-master\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 687, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!            ^^^^^^^^^^^^^^^^^^
npm ERR!   File "C:\Users\lohuama\Documents\insta.js-master\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 679, in main
npm ERR!     return gyp_main(args)
npm ERR!            ^^^^^^^^^^^^^^
npm ERR!   File "C:\Users\lohuama\Documents\insta.js-master\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 645, in gyp_main
npm ERR!     [generator, flat_list, targets, data] = Load(
npm ERR!                                             ^^^^^
npm ERR!   File "C:\Users\lohuama\Documents\insta.js-master\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 151, in Load
npm ERR!     result = gyp.input.Load(
npm ERR!              ^^^^^^^^^^^^^^^
npm ERR!   File "C:\Users\lohuama\Documents\insta.js-master\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 3052, in Load
npm ERR!     LoadTargetBuildFile(
npm ERR!   File "C:\Users\lohuama\Documents\insta.js-master\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 411, in LoadTargetBuildFile
npm ERR!     build_file_data = LoadOneBuildFile(
npm ERR!                       ^^^^^^^^^^^^^^^^^
npm ERR!   File "C:\Users\lohuama\Documents\insta.js-master\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 239, in LoadOneBuildFile
npm ERR!     build_file_contents = open(build_file_path, "rU").read()
npm ERR!                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! ValueError: invalid mode: 'rU' while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\lohuama\Documents\insta.js-master\node_modules\node-gyp\lib\configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lohuama\\Documents\\insta.js-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\lohuama\Documents\insta.js-master\node_modules\re2
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v7.1.0
npm ERR! gyp ERR! not ok
npm ERR! node:internal/process/promises:279
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR!
npm ERR! [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
npm ERR!   code: 'ERR_UNHANDLED_REJECTION'
npm ERR! }

npm ERR! A complete log of this run can be found in:
